DROP TABLE IF EXISTS STUDENT, SUBJECT, ENROLLMENT;

CREATE TABLE STUDENT
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(150)
);

CREATE TABLE SUBJECT
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE ENROLLMENT
(
    id SERIAL PRIMARY KEY,
    student_id INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    FOREIGN KEY (student_id) REFERENCES STUDENT(id),
    FOREIGN KEY (subject_id) REFERENCES SUBJECT(id)
)